# Generated by Django 4.1.7 on 2023-04-12 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuEntrada",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ds_MenuEntrada", models.CharField(max_length=50)),
                ("ordem", models.CharField(max_length=50)),
                ("nomePagina", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="nivelAcesso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ds_nivelAcesso", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=255)),
                ("senha", models.CharField(max_length=255)),
                ("nome", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=1)),
                ("inclusao", models.DateField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuarioNivelAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_nivelAcesso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuario.nivelacesso",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuario.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NivelEntradaMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MenuEntrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuario.menuentrada",
                    ),
                ),
                (
                    "nivelAcesso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuario.nivelacesso",
                    ),
                ),
            ],
        ),
    ]
