# Generated by Django 4.2 on 2023-04-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_alter_usuario_senha_alter_usuario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
