# Generated by Django 4.2 on 2023-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0003_alter_usuario_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario", name="senha", field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="usuario", name="usuario", field=models.CharField(),
        ),
    ]
