# Generated by Django 4.2 on 2023-04-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0004_alter_usuario_senha_alter_usuario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="inclusao",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="login",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
