# Generated by Django 4.2.1 on 2023-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[(1, 'Ativado'), (0, 'Destivado')], max_length=1),
        ),
    ]
