# Generated by Django 4.2.1 on 2023-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_usuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('1', 'Ativado'), ('0', 'Desativado')], max_length=1),
        ),
    ]
