# Generated by Django 4.2 on 2023-05-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0013_alter_usuario_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario", name="status", field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="usuarionivelacesso",
            name="id_nivelAcesso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios_nivel",
                to="usuario.nivelacesso",
            ),
        ),
        migrations.AlterField(
            model_name="usuarionivelacesso",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="niveis_acesso",
                to="usuario.usuario",
            ),
        ),
    ]
