# Generated by Django 4.2 on 2023-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0014_alter_usuario_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuarionivelacesso", name="id_usuario",),
        migrations.AddField(
            model_name="usuarionivelacesso",
            name="id_usuarios",
            field=models.ManyToManyField(to="usuario.usuario"),
        ),
        migrations.RemoveField(model_name="usuarionivelacesso", name="id_nivelAcesso",),
        migrations.AddField(
            model_name="usuarionivelacesso",
            name="id_nivelAcesso",
            field=models.ManyToManyField(to="usuario.nivelacesso"),
        ),
    ]
