# Generated by Django 4.2 on 2023-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0016_nivelacesso_id_usuarios_delete_usuarionivelacesso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nivelacesso",
            name="id_usuarios",
            field=models.ManyToManyField(
                related_name="niveisacesso", to="usuario.usuario"
            ),
        ),
    ]
