# Generated by Django 4.2 on 2023-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0017_alter_nivelacesso_id_usuarios"),
    ]

    operations = [
        migrations.RemoveField(model_name="nivelacesso", name="id_usuarios",),
        migrations.RemoveField(model_name="usuario", name="login",),
        migrations.AddField(
            model_name="usuario",
            name="id_niveis",
            field=models.ManyToManyField(
                related_name="usuarios", to="usuario.nivelacesso"
            ),
        ),
    ]
