# Generated by Django 4.2 on 2023-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuario",
            "0018_remove_nivelacesso_id_usuarios_remove_usuario_login_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuentrada",
            name="nivel_MenuEntrada",
            field=models.IntegerField(default=0),
        ),
    ]
