# Generated by Django 4.2 on 2023-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0019_menuentrada_nivel_menuentrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuentrada",
            name="id_niveis",
            field=models.ManyToManyField(
                related_name="menusEntrada", to="usuario.nivelacesso"
            ),
        ),
    ]
