# Generated by Django 4.2 on 2023-06-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0020_menuentrada_id_niveis"),
    ]

    operations = [
        migrations.DeleteModel(name="NivelEntradaMenu",),
    ]
