# Generated by Django 4.2 on 2023-06-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0021_delete_nivelentradamenu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuentrada", old_name="nomePagina", new_name="nomepagina",
        ),
    ]
