# Generated by Django 4.2.1 on 2023-06-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_rename_nomepagina_menuentrada_nomepagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentrada',
            name='id_niveis',
        ),
        migrations.CreateModel(
            name='NivelEntradaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuEntrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.menuentrada')),
                ('nivelAcesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.nivelacesso')),
            ],
        ),
    ]
