# Generated by Django 4.2.1 on 2023-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_remove_menuentrada_id_niveis_nivelentradamenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentrada',
            name='id_niveis',
            field=models.ManyToManyField(related_name='menus', to='usuario.nivelacesso'),
        ),
        migrations.DeleteModel(
            name='NivelEntradaMenu',
        ),
    ]
