# Generated by Django 4.2 on 2023-06-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0024_menuentrada_id_niveis_delete_nivelentradamenu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario", name="senha", field=models.CharField(max_length=128),
        ),
    ]
