# Generated by Django 4.2.2 on 2023-06-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_alter_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
