# Generated by Django 4.2.2 on 2023-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0026_remove_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='nome@email.com', max_length=150, unique=True),
        ),
    ]
