# Generated by Django 4.2.2 on 2023-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='nome@email.com', max_length=50),
        ),
    ]
