# Generated by Django 4.2.2 on 2023-06-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_remove_usuario_username_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='nome@email.com', max_length=150, unique=True),
        ),
    ]
