# Generated by Django 4.2.2 on 2023-06-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_remove_usuario_usuario_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
    ]
